import type { Project } from "./types";

export type { Project } from "./types";

export const projects: Project[] = [
    {
        slug: "55hubcorp",
        title: "55hubcorp.com — +55 HUB Platform",
        category: "Product & Platform",
        year: "2025 – present",
        featured: true,
        role: "Solo Product & Platform Engineer (CPO/CTO) — built everything end-to-end",
        oneLiner:
            "A trilingual institutional platform and its own internal CRM, shipped solo on Cloudflare's edge.",
        summary:
            "The full digital platform for +55 HUB & Corporate Group: a multilingual (PT/EN/ES) public site with an interactive Readiness Scorecard, landing pages, a properties area and an AI-assisted blog — plus a purpose-built internal CRM that turns captured leads into a deals pipeline. Designed, built, secured and deployed solo on Astro 5 running on Cloudflare Workers, with D1, R2 and Workers AI.",
        context:
            "+55 HUB & Corporate Group helps international companies and investors land and expand in Brazil — real estate, global entry, and corporate services. They needed a single platform that speaks to a PT/EN/ES audience with an executive, high-trust feel, captures qualified leads from multiple entry points, and gives the internal team a real system to work those leads — without paying for and stitching together several SaaS tools.",
        problem:
            "Two normally-separate products had to live in one codebase and one budget: a marketing-grade public site (fast, multilingual, SEO-ready, conversion-oriented) and a back-office CRM (auth, roles, pipeline, analytics). It had to be cheap to run, secure enough for B2B financial partnerships and LGPD, and maintainable by a single person while the business scaled traffic.",
        solution: [
            "Public site (55hubcorp.com): trilingual PT/EN/ES institutional experience, an interactive Readiness Scorecard, two conversion landing pages (Real Estate; Global Entry & Expansion), a Properties area, and a Blog.",
            "Internal CRM (app.55hubcorp.com/console): lead capture, a deals Kanban, tasks, team & users management, blog and properties admin, settings, and an analytics dashboard.",
            "One repository, two products — sharing i18n, design system, auth and data layer to keep operating cost and maintenance low.",
            "Lead-to-deal pipeline: public forms feed straight into the CRM, so marketing capture and sales work happen in the same system.",
            "AI-assisted content: blog posts authored in Portuguese are auto-translated to EN and ES via Workers AI, keeping all three locales in sync without manual duplication.",
        ],
        highlights: [
            "Astro 5 (SSR + static islands) on Cloudflare Workers — edge-rendered, globally fast.",
            "Cloudflare D1 (SQLite) for data, R2 for file storage, Workers AI for PT→EN/ES blog translation.",
            "i18n via deep-merge: Portuguese is the base locale; EN/ES are overrides, missing keys fall back to PT — no blank strings.",
            "Interactive world globe on the home page: Canvas 2D via d3-geo + world-atlas, lazy-mounted through requestIdleCallback, pauses off-screen, static under prefers-reduced-motion.",
            "React island Readiness Scorecard with a radar chart — JS shipped only where it's needed.",
            "Lead → CRM pipeline hardened with Turnstile anti-bot, same-origin CSRF protection, and input sanitization.",
            "5-role RBAC hierarchy (viewer < closer < gestor < admin < super_admin) with per-owner data segregation.",
            "Security engineering: PBKDF2 + salt password hashing, hashed session tokens, login rate-limiting (per email and IP), CSP / HSTS / X-Content-Type-Options headers.",
            "Analytics funnel: conversion by stage, revenue won/lost, loss reasons and lead source, plus Cloudflare Web Analytics.",
        ],
        stack: [
            "Astro 5",
            "Cloudflare Workers",
            "Cloudflare D1 (SQLite)",
            "Cloudflare R2",
            "Workers AI",
            "React (islands)",
            "TypeScript",
            "Tailwind CSS v4",
            "d3-geo",
            "Turnstile",
        ],
        tags: ["Astro 5", "Cloudflare Workers", "D1", "Workers AI", "TypeScript"],
        metrics: [
            { value: "PT / EN / ES", label: "Trilingual, single codebase" },
            { value: "2 products", label: "Public site + internal CRM, one repo" },
            { value: "5 roles", label: "RBAC with data segregation" },
            { value: "Edge-native", label: "Astro 5 on Cloudflare Workers" },
        ],
        links: [
            { label: "Live site", href: "https://55hubcorp.com" },
            { label: "CRM app", href: "https://app.55hubcorp.com" },
        ],
        demo: "https://55hubcorp.com",
        screenshots: [
            { src: "/projects/55hubcorp/site.png", url: "55hubcorp.com" },
            { src: "/projects/55hubcorp/crm.png", url: "app.55hubcorp.com/console" },
        ],
        confidential: false,
    },
    {
        slug: "treinaedital",
        title: "treinaedital.com.br — TreinaEdital (Aprovaki)",
        category: "Product & Platform",
        year: "2025 – present",
        role: "Founder & CEO — product vision and full-stack build",
        oneLiner:
            "A study platform for Brazilian public exams: three apps, payments and AI-generated questions, founded and built end-to-end.",
        summary:
            "TreinaEdital, by Aprovaki, is a study platform for Brazilian concursos públicos: students buy access to a specific exam and study through text lessons, AI-assisted question practice, timed mock exams, performance tracking and a ranking against real vacancies. Built as a Turborepo monorepo with three Next.js apps (public site, student app, admin) over a shared package layer, with Stripe payments, mandatory 2FA and Anthropic Claude for question generation. As founder and CEO, I own product, engineering and go-to-market.",
        context:
            "Candidates for Brazilian public-service exams often fail not from lack of effort but from studying the wrong material. TreinaEdital focuses each candidate only on what their specific edital actually charges — subject by subject, weighted by importance — with a ranking that compares performance against the real number of vacancies.",
        problem:
            "Delivering this meant three distinct products (a selling public site, a student learning app, and an admin to run exams, content, sales and marketing) on one secure, payment-grade platform: money never trusted from the browser, webhooks idempotent, admin protected by 2FA, content behind signed links, and a question bank that can grow with AI without losing quality.",
        solution: [
            "Turborepo + pnpm monorepo: apps/web (public site + checkout), apps/app (student), apps/admin (operations), plus a shared @treinaedital/* package layer.",
            "One-time purchase per exam with lifetime access, priced server-side; an all-access subscription on the roadmap.",
            "Stripe payments (card and Pix) with signed, idempotent webhooks, so a single event never grants access twice.",
            "PostgreSQL with Prisma; NextAuth v5 with mandatory TOTP 2FA for admin; LGPD routines.",
            "AI question generation and PDF exam extraction with Anthropic Claude, output validated by zod, with a configurable model and a spend cap.",
            "Cloudflare R2 for content behind signed links; Resend for transactional email; Upstash Redis for rate-limit and cache; Sentry, PostHog, GA4 and Meta Pixel for observability and analytics.",
        ],
        highlights: [
            "Founder and CEO: set the product vision and built the platform end-to-end.",
            "Three-app Turborepo monorepo (web, student app, admin) over a shared package layer.",
            "Server-side pricing plus signed, idempotent Stripe webhooks (card and Pix) — access never double-granted.",
            "Admin locked behind NextAuth v5 with mandatory TOTP 2FA; a dedicated security package (crypto, rate-limit, signed tokens, antifraud, audit).",
            "AI question generation and PDF extraction with Anthropic Claude, zod-validated and cost-capped.",
            "PostgreSQL / Prisma, Cloudflare R2 signed links, Upstash Redis, Resend, Sentry and PostHog.",
        ],
        stack: [
            "Next.js 15",
            "React 19",
            "TypeScript",
            "Turborepo",
            "PostgreSQL",
            "Prisma",
            "NextAuth v5",
            "Stripe",
            "Cloudflare R2",
            "Anthropic Claude",
            "Upstash Redis",
            "Resend",
            "Sentry",
            "Tailwind CSS",
        ],
        tags: ["Next.js 15", "Turborepo", "Stripe", "PostgreSQL", "Claude AI"],
        metrics: [
            { value: "3 apps", label: "Site, student app, admin" },
            { value: "Founder & CEO", label: "Product and full-stack build" },
            { value: "Card + Pix", label: "Stripe, server-side pricing" },
            { value: "AI questions", label: "Claude, zod-validated" },
        ],
        links: [{ label: "treinaedital.com.br", href: "https://treinaedital.com.br" }],
        demo: "https://treinaedital.com.br",
        screenshots: [{ src: "/projects/treinaedital/site.png", url: "treinaedital.com.br" }],
        confidential: false,
    },
    {
        slug: "distopico-solutions",
        title: "distopicoglobal.com — Distópico Solutions",
        category: "Product & Platform",
        year: "2026 – present",
        role: "CPTO — built the multilingual site and admin end-to-end",
        oneLiner:
            "The multilingual site and admin panel for Distópico, a global creative holding, on Next.js 16 and Cloudflare's edge.",
        summary:
            "The institutional multilingual (PT/EN/ES) website and admin panel for Distópico Solutions, a global creative holding built on results over appearance. A public site presenting the holding's five verticals, method and manifesto, plus a custom admin (auth, RBAC, leads, analytics, SEO, audit log), shipped on Next.js 16 running on Cloudflare Workers with D1, R2 and KV.",
        context:
            "Distópico Solutions is a global creative holding that governs a company's whole revenue architecture — strategy, creation, distribution, performance, reputation and measurement — under one integrated cycle, across five verticals (Performance, AD, Influence, Films, Academy). It needed a high-craft trilingual presence that feels like the brand (\"resultado acima de aparência\") and a real back office to capture and work leads.",
        problem:
            "The site had to feel premium and alive (motion from start to finish) while staying fast and SEO-ready in three languages with translated slugs and hreflang, and it had to ship with a genuine admin (auth, roles, leads, analytics, audit) rather than a static brochure — all cheap to run and maintainable solo.",
        solution: [
            "Public site in PT/EN/ES with next-intl: translated slugs per language and hreflang, covering home, Ecosystem (5 verticals), Method, Manifesto, Academy, Contact and legal pages.",
            "Custom admin panel (noindex): dashboard, leads, analytics, SEO editor, users and audit log.",
            "Own auth: Argon2id password hashing, 256-bit opaque DB-backed sessions, owner/admin/editor/viewer RBAC, forced temporary-password reset and audit logging.",
            "Animated \"Rede Viva\" living-network background (Canvas 2D) with motion + lenis, honoring prefers-reduced-motion.",
            "Drizzle ORM over SQLite in dev (better-sqlite3) and Cloudflare D1 in production, from one schema.",
            "Deployed on Cloudflare Workers via @opennextjs/cloudflare (D1 + R2 + KV).",
        ],
        highlights: [
            "Next.js 16 (App Router, React 19): SSG on the public pages, dynamic on admin and API.",
            "Trilingual by design with next-intl: translated slugs, hreflang and full PT/EN/ES parity.",
            "Custom Argon2id auth with DB sessions, 4-role RBAC and an audit log — no third-party auth SaaS.",
            "\"Rede Viva\" Canvas 2D animated background, motion + lenis, reduced-motion aware.",
            "Drizzle ORM: SQLite in dev and Cloudflare D1 in production from a single schema.",
            "Edge deploy via @opennextjs/cloudflare on Workers with D1, R2 and KV.",
        ],
        stack: [
            "Next.js 16",
            "React 19",
            "next-intl",
            "Tailwind CSS v4",
            "Drizzle ORM",
            "Cloudflare D1",
            "Cloudflare R2",
            "Cloudflare KV",
            "Cloudflare Workers",
            "Argon2id",
            "TypeScript",
        ],
        tags: ["Next.js 16", "Cloudflare Workers", "next-intl", "Drizzle", "RBAC"],
        metrics: [
            { value: "PT / EN / ES", label: "Trilingual, translated slugs" },
            { value: "5 verticals", label: "Holding ecosystem" },
            { value: "Site + admin", label: "Public site and back office" },
            { value: "Edge-native", label: "Next.js 16 on Cloudflare" },
        ],
        links: [{ label: "distopicoglobal.com", href: "https://distopicoglobal.com/pt" }],
        demo: "https://distopicoglobal.com/pt",
        screenshots: [{ src: "/projects/distopico/site.png", url: "distopicoglobal.com" }],
        confidential: false,
    },
    {
        slug: "gov-systems-websis",
        title: "Mission-Critical Government Systems",
        category: "Enterprise / Government",
        year: "2022 – 2025",
        role: "Fullstack .NET Developer → Scrum Master",
        oneLiner:
            "Building and leading delivery of high-stakes systems for Brazilian federal agencies.",
        summary:
            "Development and agile delivery of mission-critical systems for Brazilian government bodies — ANTT (national land-transport agency), SEST SENAT, and SISRH — across a .NET / SQL Server / Angular stack. Grew from intern to fullstack developer to Scrum Master, shipping features and executive Power BI dashboards for public-sector operations.",
        context:
            "Websis Tecnologia builds and operates software for the Brazilian federal government. These systems support real regulatory and administrative operations, where availability, correctness and auditability are non-negotiable. The work spanned an intern year, a fullstack developer phase, and a Scrum Master phase leading delivery.",
        problem:
            "Public-sector systems carry strict requirements around reliability, data integrity and traceability, worked on by teams that must ship predictably against agency expectations. The challenge: deliver correct, performant features on a mature enterprise stack while keeping the team's cadence tight and stakeholder-visible.",
        solution: [
            "Developed and maintained features for ANTT, SEST SENAT and SISRH on a C# / ASP.NET (MVC) backend with Angular front-ends.",
            "Data access with both Dapper and Entity Framework over SQL Server, choosing the right tool per query-path.",
            "Integrated Elasticsearch for fast search over large operational datasets.",
            "Built executive Power BI dashboards giving leadership operational visibility.",
            "As Scrum Master, ran agile ceremonies and protected team cadence and delivery predictability.",
        ],
        highlights: [
            "Progression from Software Developer Intern → Fullstack .NET Developer → Scrum Master on the same mission-critical program.",
            "Enterprise .NET stack: C# / ASP.NET / MVC, Dapper + Entity Framework, SQL Server.",
            "Elasticsearch-backed search over operational data.",
            "Power BI executive dashboards for public-sector leadership.",
            "Agile leadership (Scrum) on government delivery with real accountability.",
        ],
        stack: [
            "C# / .NET",
            "ASP.NET (MVC)",
            "Angular",
            "Dapper",
            "Entity Framework",
            "SQL Server",
            "Elasticsearch",
            "Power BI",
            "Scrum",
        ],
        tags: ["C# / .NET", "Angular", "SQL Server", "Elasticsearch", "Scrum"],
        metrics: [
            { value: "3 agencies", label: "ANTT · SEST SENAT · SISRH" },
            { value: "Intern → SM", label: "Developer to Scrum Master" },
            { value: "Power BI", label: "Executive dashboards delivered" },
        ],
        confidential: true,
    },
    {
        slug: "cboo-modernization",
        title: "CBOO — Legacy Modernization & Database Architecture",
        category: "Modernization",
        year: "2024 – present",
        role: "Software Engineer & Database Administrator (freelance)",
        oneLiner:
            "Modernizing a legacy PHP/Bootstrap system to Vue.js — and re-architecting the database beneath it.",
        summary:
            "Full-stack modernization for CBOO (Conselho Brasileiro de Óptica e Optometria): migrating a legacy PHP/Bootstrap application to a Vue.js front-end while re-architecting the MySQL schema, migrating data, and tuning performance as the acting DBA — backups, access control, indexing and SQL optimization.",
        context:
            "CBOO is Brazil's council for optics and optometry. Its existing web system was a legacy PHP/Bootstrap application that needed modernizing for maintainability and a better user experience, while the underlying database needed real architectural and performance work.",
        problem:
            "Legacy code and an under-optimized database limited maintainability and performance. The system needed a modern front-end, a sound relational schema, safe data migration off the old structure, and ongoing database administration — all delivered by one engineer working directly with the organization.",
        solution: [
            "Led the full-stack modernization: legacy PHP/Bootstrap → a Vue.js front-end.",
            "Re-architected the MySQL schema and performed the data migration from the legacy structure.",
            "SQL optimization, performance tuning and indexing for faster, more reliable queries.",
            "Acting DBA: backups, access control, and day-to-day administration via phpMyAdmin and the CLI.",
            "Applied Clean Code practices to leave a maintainable codebase.",
        ],
        highlights: [
            "End-to-end ownership: front-end modernization + database architecture + DBA, solo.",
            "Legacy PHP/Bootstrap replaced with a Vue.js front-end.",
            "MySQL schema re-architecture with a real data migration path.",
            "Performance work: query optimization, indexing, tuning.",
            "Database administration: backups and access control (phpMyAdmin + CLI).",
        ],
        stack: [
            "Vue.js",
            "PHP (legacy)",
            "Bootstrap (legacy)",
            "MySQL",
            "phpMyAdmin",
            "SQL / DBA",
            "Clean Code",
        ],
        tags: ["Vue.js", "MySQL", "PHP", "DBA", "Performance"],
        metrics: [
            { value: "PHP → Vue.js", label: "Legacy front-end modernized" },
            { value: "Re-architected", label: "MySQL schema + data migration" },
            { value: "Since 2024", label: "Ongoing engagement" },
        ],
        demo: "https://cboobrasil.org.br",
        links: [{ label: "cboobrasil.org.br", href: "https://cboobrasil.org.br" }],
        screenshots: [{ src: "/projects/cboo/site.png", url: "cboo.org.br" }],
        confidential: false,
    },
];
